# Generated by Django 5.2.1 on 2025-05-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bati',
            name='id',
        ),
        migrations.AddField(
            model_name='bati',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bati',
            name='indexbatiment',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='bati',
            name='sitaution_geo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bati',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bati',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
