# Generated by Django 5.2.1 on 2025-05-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0002_remove_bati_id_bati_altitude_bati_indexbatiment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bati',
            old_name='indexbatiment',
            new_name='id',
        ),
    ]
