# Generated by Django 5.2.1 on 2025-05-30 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bati', '0003_rename_indexbatiment_bati_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Patrimonialite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.RenameField(
            model_name='bati',
            old_name='sitaution_geo',
            new_name='situation_geo',
        ),
        migrations.AddField(
            model_name='bati',
            name='cadastre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bati.cadastre'),
        ),
        migrations.AddField(
            model_name='bati',
            name='patrimonialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bati.patrimonialite'),
        ),
        migrations.AddField(
            model_name='bati',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bati.proprietaire'),
        ),
    ]
